module.exports = {
  mode: "jit",
  purge: ["./public/index.html"],
  darkMode: false, // or 'media' or 'class'
  theme: {
    extend: {
      fontFamily: {
        montserrat: ["Montserrat", "sans-serif"],
        fontAwesome5free: ["Font Awesome 5 Free"],
      },
      colors: {
        footerBG: "#F9F9F9",
        customGray: "#686868",
        customBlue: "#00A3E1",
        bannerOverlayColor: "#0A0A0A",
        dropDownBorderColor: "#13aff0",
        ddBorderBottomColor: "#f1f1f1",
        ddItemHoverBG: "#F8F8F8",
        contactInfoBG: "#E9F6F8",
        contactInfoGradientFrom: "#792cff",
        contactInfoGradientTo: "#06bdf4",
        gradientBtnOrange: "#FF8A66",
        gradientBtnPink: "#FF4570",
        inputBorder: "#999",
        btnBorder: "#ff2350",
        textColor: "#2d2d2d",
        selectOptColor: "#C05C5A",
        footerTextColor: "#474747",
        footerTextColorDark: "#2D2D2D",
        starsYellow: "#FBE122",
        textColorOpaque: "rgba(45, 45, 45, 0.6)",
        textColorMoreOpaque: "rgba(45, 45, 45, 0.4)",
        formInputsBG: "#FCFCFC",
        formInputsBorder: "#F2F2F2",
        grayBG: "#F1F1F1",
        grayText: "#333",
        sideMenuText: "#555",
        sideMenuItemBorder: "rgba(0,0,0,0.035)",
        sideMenuArrowBG: "#fbfbfb",
        inherit: "inherit",
      },
      backgroundImage: {
        contactUsTexture: "url('./assets/images/colorful-texture.jpg')",
        headerBannerBG: "url('./assets/images/dukesmeadowgolfclub.jpg')",
        headerBannerBGmobile: "url('./assets/images/santa.jpg')",
        headerBannerOverlay: "url('./assets/images/header-opacity.jpg')",
        aboutCFbg: "url('./assets/images/bg01.jpg')",
        clientsBG: "url('./assets/images/children-at-disco.jpg')",
        teamBG: "url('./assets/images/gallery-bg.jpg')",
        blueBG: "url('./assets/images/blue-bg.jpg')",
        valuesBG: "url('./assets/images/wellbeing-girls-hugging.jpg')",
      },
      backgroundPosition: {
        "top-center": "top center",
        "bottom-center": "bottom center",
      },
      screens: {
        lg1191: "1191px",
        lg1200: "1200px",
        lg1150: "1150px",
        md861: "861px",
        sm565: "565px",
      },
      spacing: {
        "25vw": "25vw",
        "70px": "70px",
        "49%": "49%",
        "80%": "80%",
        "30%": "30%",
        "7%": "7%",
        "12%": "12%",
        "1%": "1%",
        "10%": "10%",
        "15%": "15%",
        "5%": "5%",
        "3%": "3%",
        "5px": "5px",
        "13px": "13px",
        "15px": "15px",
        "-15px": "-15px",
        "27px": "27px",
        "30px": "30px",
        "60px": "60px",
        "66px": "66px",
        "300px": "300px",
      },
      letterSpacing: {
        "0.6px": "0.6px",
      },
      zIndex: {
        "-1": "-1",
        999999: "999999",
      },
      skew: {
        "-9": "-9deg",
      },
      borderWidth: {
        fullVW: "100vw",
        "200px": "200px",
      },
      borderRadius: {
        "50%": "50%",
        "3px": "3px",
        "50px": "50px",
      },
      boxShadow: {
        customBoxShadow: "0 2px 6px rgb(0 0 0 / 10%)",
        sbmtBtnShadow: "0px 0px 25px 5px rgb(0 0 0 / 20%)",
        getInTouchBtnShadow: "0px 0px 25px 5px #ffffff",
      },
      dropShadow: {
        bannerTextShadow: "5px 5px 5px #fff",
      },
      lineHeight: {
        0: "0",
        1.2: "1.2",
        1.4: "1.4",
      },
      fontSize: {
        "30px": "30px",
        "40px": "40px",
        "60px": "60px",
        "2.5rem": "2.5rem",
        "5rem": "5rem",
        "14px": "14px",
        "15px": "15px",
        "-15px": "-15px",
        "11px": "11px",
      },
      flexGrow: {
        2: "2",
        3: "3",
      },
      flex: {
        basis43: "0 1 43%",
        basis20: "0 1 35%",
        basis60: "0 1 55%",
      },
      transitionProperty: {
        left: "left",
      },
      transitionTimingFunction: {
        ease: "ease",
      },
      transitionDelay: {
        0: "0ms",
      },
    },
  },
  variants: {
    extend: {},
    varients: {
      display: ["group-hover"],
    },
  },
  plugins: [],
};
